name: main
on: [push]
jobs:
  check-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install --upgrade pip poetry
      - run: poetry install
      - run: poetry run make check-test
  check-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - run: pip install --upgrade pip poetry
      - run: poetry install
      - run: poetry run make check-lint
      - run: poetry run make check-format
      - run: poetry run poetry build
